# Use the official Redis image as a base image
FROM redis:alpine

# Expose the default Redis port
EXPOSE 6379

# Define a health check for Redis
HEALTHCHECK --interval=5s --timeout=5s \
  CMD redis-cli ping || exit 1

# Run the Redis server
CMD ["redis-server"]

